#!/bin/bash
#./make_dir_hw [HW#]

if [ ! -d "files" ]; then
        mkdir files; 
fi
cd files/
dirs=("students" "results" "testcases" "solutions")
for(( i=0;i<${#dirs[@]};i++));do
    if [ ! -d "${dirs[$i]}" ]; then
        mkdir "${dirs[$i]}";
    fi
    cd "${dirs[$i]}";
    
    if [ ! -d "HW$1" ]; then
        mkdir "HW$1";
    fi
    cd ..;

done
