#!/bin/bash
#./mark_test [HW dir] [problem#]
cd $1
for i in $(ls *.c);do
     exec=${i%.c};
     gcc -o $exec $i;
     ./$exec > ../$2/$exec;
     rm $exec;
done
cd ../$2
for i in $(ls);do
    diff -b -u ../$3 $i >> ../diffs;
done
